AWSTemplateFormatVersion: "2010-09-09"
Description: Payment Service DynamoDB Table

Resources:

  PaymentMethodsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PaymentMethods
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: card_token
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: card_token
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

Outputs:
  TableName:
    Value: !Ref PaymentMethodsTable
