version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: account-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/db.json:/app/db.json
